README: update installation instructions
habitat-sh/habitat-operator pull request #327
Opened 2018-08-03 04:51 UTC by surajssd

Add instructions to setup GOPATH and place where you can find
the installed binaries.

2018-08-07 11:32 UTC, krnowak requested changes
Also, same with #326 - consider filing another PR from our kinvolk fork, you'll get the tests. But not so important for this PR, because we skip the tests on the PRs with changes only in documentation.

2018-08-07 11:32 UTC, krnowak commented on README.md
> -If you built the operator manually, you'll have to specify the path to the binary. So from the root of the source directory, run:
I'm not sure why did you drop this snippet - `make build` does not put the `habitat-operator` binary anywhere in `$PATH` (unless you have `.` or `$GOPATH/src/github.com/habitat-sh/habitat-operator` in `$PATH`, which is unlikely).

2018-08-07 11:32 UTC, krnowak commented on README.md
> -If you built the operator manually, you'll have to specify the path to the binary. So from the root of the source directory, run:
But obviously, it would be nice to somehow unify the invocations. Maybe by telling the user to optionally put the built binary somewhere in the `$PATH` or by instructing the user to take the location of the `habitat-operator` binary into account (so use `./habitat-operator` whenever `habitat-operator` is mentioned) or somesuch.

2018-08-07 11:32 UTC, krnowak commented on README.md
> -##### Cluster with RBAC disabled
Why dropping it?

2018-08-07 11:55 UTC, surajssd commented on README.md
> -##### Cluster with RBAC disabled
isn't it safe to assume that all the kubernetes clusters come with RBAC enabled by default?

2018-08-07 12:38 UTC, surajssd commented on README.md
> -If you built the operator manually, you'll have to specify the path to the binary. So from the root of the source directory, run:
Yep added the line to put the binary in `PATH` after `make build`

2018-08-07 12:43 UTC, krnowak commented on README.md
> -##### Cluster with RBAC disabled
I'm not really sure about it. Maybe instead of removing it, add a note that currently most k8s clusters have RBAC enabled by default, so using this approach may result in non-working operator.

2018-08-07 13:31 UTC, surajssd commented on README.md
> -##### Cluster with RBAC disabled
if an operator will become unusable by doing this then why even document it?

2018-08-13 10:07 UTC, krnowak commented on README.md
> -##### Cluster with RBAC disabled
The operator works fine in the cluster that has RBAC disabled. Where the operator won't work is the cluster that has RBAC enabled, but it has no proper rules for the habitat-operator.

2018-08-15 07:37 UTC, krnowak requested changes

2018-08-15 07:37 UTC, krnowak commented on README.md
> +- Kubernetes cluster with version `1.9.x`, `1.10.x` or `1.11.x`.
This change should rather not be a part of this PR - adding support for 1.11 and dropping it for 1.8 should be a separate thing, as it also involves changing circleCI config.

2018-08-15 07:37 UTC, krnowak commented on README.md
> +Make sure you have [golang compiler](https://golang.org/dl/) installed and [`GOPATH`, `GOBIN` are set](https://github.com/golang/go/wiki/SettingGOPATH). Then run following command:
Golang wiki says that you should not be touching `GOBIN` unless you know what you are doing (https://github.com/golang/go/wiki/InstallTroubleshooting#environment), so just use "`GOPATH` is set".

2018-08-15 07:37 UTC, krnowak commented on README.md
> +This will put the built binary in `GOBIN`, make sure it is in your `PATH`.
Since we don't want to talk about `GOBIN` at all, please just use `GOPATH/bin`.

2018-08-15 07:37 UTC, krnowak commented on README.md
> +    cd ${GOPATH:-$HOME/go}/src/github.com/habitat-sh/habitat-operator
I'd mention just `${GOPATH}` instead `${GOPATH:-$HOME/go}` to make thing simpler.

2018-08-15 07:37 UTC, krnowak commented on README.md
> +Make sure you have [golang compiler](https://golang.org/dl/) installed and [`GOPATH`, `GOBIN` are set](https://github.com/golang/go/wiki/SettingGOPATH). Then run following command:
You can also mention that even if the user decides to skip setting GOPATH (to use the default), we will assume that the GOPATH is actually set.

2018-08-15 07:37 UTC, krnowak commented on README.md
> +Now you can see a binary `habitat-operator` available. Now put this binary in `PATH`.
How about:

This command will create a `habitat-operator` binary in the source directory. Copy this file somewhere to your `PATH`."

?

2018-08-16 10:43 UTC, surajssd commented on README.md
> +- Kubernetes cluster with version `1.9.x`, `1.10.x` or `1.11.x`.
done

2018-08-16 10:43 UTC, surajssd commented on README.md
> +Make sure you have [golang compiler](https://golang.org/dl/) installed and [`GOPATH`, `GOBIN` are set](https://github.com/golang/go/wiki/SettingGOPATH). Then run following command:
done

2018-08-16 10:43 UTC, surajssd commented on README.md
> +This will put the built binary in `GOBIN`, make sure it is in your `PATH`.
done

2018-08-16 10:43 UTC, surajssd commented on README.md
> +    cd ${GOPATH:-$HOME/go}/src/github.com/habitat-sh/habitat-operator
Using this because even if the `GOPATH` is not set then `go` uses default path as `$HOME/go` as `GOPATH`. So this will always pass and not fail.

2018-08-16 10:43 UTC, surajssd commented on README.md
> +Now you can see a binary `habitat-operator` available. Now put this binary in `PATH`.
done

2018-08-16 12:35 UTC, surajssd commented
@krnowak updated :-)

2018-08-16 17:41 UTC, krnowak submitted a review, later dismissed
Could you also check if you have addressed all the issues from #322 and #298?

2018-08-16 17:41 UTC, krnowak commented on README.md
> +Make sure you have [golang compiler](https://golang.org/dl/) installed. Then run following command:
Hm, could you add a sentence about following the installation instructions to learn about `$GOPATH` we mention later?

2018-08-31 06:16 UTC, surajssd commented on README.md
> +Make sure you have [golang compiler](https://golang.org/dl/) installed. Then run following command:
@krnowak I have updated this, this fall off the plate since was taking care of other things :-)

2019-01-16 23:50 UTC, jamesc approved these changes
Followed install instructions, all look good.

2019-01-16 23:50 UTC, merged